schema {
    mutation: Mutation
    query: Query
}

type User
{
    id: Int!
    name: String!
    email: String
    defaultHousehold: Household
    memberHouseholds: [Household]
    ownedHouseholds: [Household]
}

type Household
{
    id: Int!
    name: String!
    location: String!
    owner: User!
    folder: String
    storages: [Storage]
    users: [User]
}

type Storage
{
    id: Int!
    name: String!
    type: String!
    foodItems: [FoodItem]
}

type FoodItem
{
    id: Int!
    name: String!
    storage: Storage
    enteredBy: User!
    entered: String
    expiration: String
    filename: String
    tags: [String]
}


type Invite
{
    id: String!
    householdName: String!
    inviteeName: String
    inviterName: String!
    message: String!
    status: Int!
}

type Suggestion
{
    name: String
    tags: [String]
    filename: String
}

type InvitesPayload
{
    invites: [Invite]
    error: String
}

type AuthPayload
{
    token: String
    error: String
}

type HouseholdsPayload
{
    households: [Household]
    error: String
}

type StoragesPayload
{
    storages: [Storage]
    error: String
}

type UsersPayload
{
    users: [User]
    error: String
}

type FoodItemsPayload
{
    foodItems: [FoodItem]
    error: String
}

type RemovalPayload
{
    id: Int
    success: Int!
    error: String
}

type SuggestionPayload
{
    suggestion: Suggestion
    error: String
}

type Mutation {
    signup(email: String!, password: String!, name: String!): AuthPayload
    login(email: String!, password: String!): AuthPayload

    editUsername(email: String!, password: String!): AuthPayload
    editPassword(password: String!, oldPassword: String!): AuthPayload

    changeDefaultHousehold(householdId: Int!): HouseholdsPayload

    refreshToken: AuthPayload
    
    createHousehold(name: String!, location: String!) : HouseholdsPayload
    updateHousehold(name: String, location: String, householdId:Int!) : HouseholdsPayload
    
    addStorageToHousehold(name: String!, storageType: String!, householdId: Int!) : StoragesPayload
    updateStorage(name: String, storageType:String, storageId: Int!): StoragesPayload
    
    addFoodItemToStorage(name: String!, storageId: Int!, expiration: String, tags: [String], entered: String, filename: String): FoodItemsPayload
    updateFoodItem(foodItemId: Int! name: String, expiration: String, tags: [String] ): FoodItemsPayload
    addTagsToFoodItem(tags: [String]!, foodItemId: Int!): FoodItemsPayload
    removeTagsFromFoodItem(tags: [String]!, foodItemId: Int!): FoodItemsPayload
    moveFoodItemToStorage(foodItemId: Int!, storageId: Int!): FoodItemsPayload

    getSuggestions(image: String) : SuggestionPayload

    inviteUserToHousehold(householdId: Int!, message: String!) : InvitesPayload
    acceptHouseholdInvite(inviteId: String!) : HouseholdsPayload
    rejectHouseholdInvite(inviteId: String!) : RemovalPayload
    deleteInvite(inviteId: String!) : RemovalPayload

    removeFoodItem(foodItemId: Int!) : RemovalPayload
    removeStorage(storageId: Int!) : RemovalPayload
    removeHousehold(householdId: Int!): RemovalPayload
    removeUserFromHousehold(userId: Int!, householdId: Int!): RemovalPayload
}

type Query {
    getOwnedHouseholds : HouseholdsPayload
    getMemberHouseholds: HouseholdsPayload
    getHousehold(householdId: Int!): HouseholdsPayload
    getStorages(householdId: Int!): StoragesPayload
    getStorage(storageId: Int!): StoragesPayload
    getFoodItemsInStorage(storageId: Int!, tagFilter:String): FoodItemsPayload
    getFoodItemsInHousehold(householdId: Int!, tagFilter:String): FoodItemsPayload
    getUser : UsersPayload
    getHouseholdMembers(householdId: Int!) : UsersPayload
    getInvites(householdId: Int!) : InvitesPayload
    getInvite(inviteId: String!): InvitesPayload
    getInviteInformation(inviteId: String!): InvitesPayload
    
}